---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.10.2020 17:34
---
function HealUnit(hero,amount,flag,eff)
    --1 или nil Сколько вылечено
    --2 Сверхлечение
    if not eff then eff="Abilities\\Spells\\Human\\Heal\\HealTarget" end
    local p=GetOwningPlayer(hero)
    local MaxHP=BlzGetUnitMaxHP(hero)
    local CurrentHP=GetUnitState(hero,UNIT_STATE_LIFE)
    local LoosingHP=MaxHP-CurrentHP
    local OverHeal=amount-LoosingHP
    local TotalHeal=amount
    if LoosingHP<=amount then TotalHeal=LoosingHP	end
    DestroyEffect(AddSpecialEffectTarget(eff,hero,"overhead"))
    SetUnitState(hero,UNIT_STATE_LIFE,CurrentHP+TotalHeal)
    if TotalHeal>1 then
        FlyTextTagHealXY(GetUnitX(hero),GetUnitY(hero),"+"..R2I(TotalHeal),p)
    end
    if not flag or flag==1 then
        return TotalHeal
    end
    if  flag==2 then
        return OverHeal
    end
end