---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.09.2020 17:25
---
--Юниты
MurgulID=FourCC('n000') -- мурлок работник
MainBaseID=FourCC('n001') -- Храм пучин, главное здание


--Способности
ReturnFastGoldID=FourCC("A000") -- возврат золоты броском
AbilityPierceID=FourCC("A001") -- Проникающая способность

--Баффы
GoldReturnID=FourCC("B000") -- отлов золота, которое попало кого-то

--Исследования
PierceResearchID=FourCC("R000") -- проникающее оружие
