---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.09.2020 0:37
---
---
do
	TimerStart(CreateTimer(), 0.11, false, function()
		InitStunReload()
	end)
end
function InitStunReload()
	local DamageTrigger = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
	end
	TriggerAddAction(DamageTrigger, function()

		local damage     = GetEventDamage() -- число урона
		if damage < 1 then return end
		local eventId         = GetHandleId(GetTriggerEventId())
		local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
		local target          = GetTriggerUnit() -- тот кто получил урон
		local caster          = GetEventDamageSource() -- тот кто нанёс урон


		if isEventDamaging then
			--BlzSetEventDamage(damage)
			if BlzGetUnitAbilityCooldownRemaining(caster,AbilityIronID)<=.01 and GetUnitAbilityLevel(caster,AbilityIronID)>0  then
				local lvl=GetUnitAbilityLevel(caster,AbilityIronID)
				local cd={20,16,12}
				BlzStartUnitAbilityCooldown(caster,AbilityIronID,cd[lvl])
				StunUnit(target,2)
			end
		end
	end)

end
