---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.09.2020 10:48
---
do
	TimerStart(CreateTimer(), 0.11, false, function()
		InitCastAbilityDefibrill()
		InitUnitMurgulDeath()
	end)
end

function InitCastAbilityDefibrill()
	local SpellTrigger = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_ENDCAST)
	end
	TriggerAddAction(SpellTrigger, function()
		if GetSpellAbilityId() == AbilityDefibrID then
			local caster=GetTriggerUnit()
			local x,y,range=GetUnitX(caster),GetUnitY(caster),200
			local e=nil
			local k=GetUnitAbilityLevel(caster,AbilityDefibrID)
			local kd=0
			--print("cast")
			GroupEnumUnitsInRange(perebor,x,y,range,nil)
			while true do
				e = FirstOfGroup(perebor)

				if e == nil then break end
				--print(GetUnitName(e)"юнит в переборе")
				if not UnitAlive(e) and  GetUnitTypeId(e)==MurgulWarriorlID and GetOwningPlayer(e)==GetOwningPlayer(caster) then --
					if IWantToBeRevive[GetHandleId(e)] and k>0 then
						k=k-1
						kd=kd+1
						--print("создаём нового")
						local new=CreateUnit(GetOwningPlayer(caster),MurgulWarriorlID,GetUnitX(e),GetUnitY(e),GetRandomInt(0,360))
						SetUnitLifePercentBJ(new,50)
						ShowUnit(e,false)
					end
					--print("Воскрешаем мертвого мурлока")
				end
				GroupRemoveUnit(perebor,e)
			end
			if kd==0 then
				--print("Не кого воскрешать, показываем радиус возвращаем ресурсы")
				FlyTextTagMiss(caster,"Нет юнитов в радиусе",GetOwningPlayer(caster))
				AddCircleAreaForUnit(caster,400,2)
				TimerStart(CreateTimer(), 0.0, false, function()
					local mana=BlzGetUnitAbilityManaCost(caster,AbilityDefibrID,k-1)
					SetUnitState(caster,UNIT_STATE_MANA,GetUnitState(caster,UNIT_STATE_MANA)+mana)
					--print(mana)
					--BlzEndUnitAbilityCooldown(caster,AbilityDefibrID)
					BlzStartUnitAbilityCooldown(caster,AbilityDefibrID,1)
				end)
			end
		end
	end)
end

IWantToBeRevive={}
function InitUnitMurgulDeath()
	local gg_trg_DEADGUI = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(gg_trg_DEADGUI, EVENT_PLAYER_UNIT_DEATH)
	TriggerAddAction(gg_trg_DEADGUI, function()
		local DeadUnit=GetTriggerUnit()
		if GetUnitTypeId(DeadUnit)==MurgulWarriorlID then
			IWantToBeRevive[GetHandleId(DeadUnit)]=true
			local sec=5
			local tag=StaticTag(sec, 0.025, GetWidgetX(DeadUnit), GetWidgetY(DeadUnit), 0, 120, 240, 120, 255, 0, 0.04, 2, 5, GetOwningPlayer(DeadUnit))
			SetTextTagVisibility(tag, false)
			local tagTimer=CreateTimer()
			local hero,kHero,heroTable=FindUnitOfType(HeroWarriorID,1000,GetUnitXY(DeadUnit))
			if kHero>1 then
				for i=1,#heroTable do
					if GetOwningPlayer(heroTable[i])==GetOwningPlayer(DeadUnit) then
						hero=heroTable[i]
						print("несколько героев видят дефибриляцию, обратитесь к автору карты")
					end
				end
			end


			TimerStart(tagTimer, 0.1, true, function()
				DestroyTextTag(tag)
				sec=sec-0.1
				local testShowed=string.format("%%02.1f",sec)
				tag=StaticTag(testShowed, 0.025, GetWidgetX(DeadUnit), GetWidgetY(DeadUnit), 0, 120, 240, 120, 255, 0, 0.04, 2, 5, GetOwningPlayer(DeadUnit))
				SetTextTagVisibility(tag, false)
				if hero then
					if IsUnitInRange(hero,DeadUnit,1000) then
						SetTextTagVisibility(tag, GetOwningPlayer(hero) == GetLocalPlayer())
					else
						SetTextTagVisibility(tag, false)
					end
				end
				if IsUnitHidden(DeadUnit) then
					DestroyTextTag(tag)
					DestroyTimer(tagTimer)
				end
			end)

			TimerStart(CreateTimer(), 5, false, function()
				--print("больше не может быть воскрешен")
				IWantToBeRevive[GetHandleId(DeadUnit)]=false
				DestroyTextTag(tag)
				DestroyTimer(tagTimer)
			end)
		end
	end )
end


function AddCircleAreaForUnit(unit,radius,timed)
		local path="replaceabletextures\\selection\\rangeindicator" -- путь до дефолтной иконки
	if not radius then
		radius=BlzGetUnitWeaponRealField(unit,UNIT_WEAPON_RF_ATTACK_RANGE,0)*2.3 -- коэффициент 2,3 подобран методом тыка и исходит из размеров текстуры
		--print(radius)
	end
	if not timed then
		timed=9999
	end
	local CircleImage=CreateImage(path,radius,radius,radius,5000,5000,0,0,0,0,4)

	SetImageRenderAlways(CircleImage, true)
	ShowImage(CircleImage,false)
	SetImagePosition(CircleImage,GetUnitX(unit),GetUnitY(unit),0)
	local alpha=255
	local str=timed
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		if GetLocalPlayer()==GetOwningPlayer(unit) then
			ShowImage(CircleImage,true)
		end
		alpha=alpha-str
		SetImageColor(CircleImage,255,0,0,alpha)
		timed=timed-TIMER_PERIOD
		local xs,ys=GetUnitX(unit)-radius/2-16,GetUnitY(unit)-radius/2-16
		SetImagePosition(CircleImage,xs,ys,0)

		if timed<=0 then
			DestroyTimer(GetExpiredTimer())
			DestroyImage(CircleImage)
			ShowImage(CircleImage,false)
		end
	end)
end