---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 28.09.2020 18:09
---
do
	TimerStart(CreateTimer(), 0.11, false, function()
		InitCastAbilityMamonite()
		InitDamageGold()
		--CreateTextTagReal = CreateTextTag
		--CreateTextTag = function()end
	end)
end

function InitCastAbilityMamonite()
	local SpellTrigger = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_ENDCAST)
	end
	TriggerAddAction(SpellTrigger, function()
		if GetSpellAbilityId() == ReturnFastGoldID then
			local caster=GetTriggerUnit()
			TimerStart(CreateTimer(), 0.1, false, function()
				ClearSourceState(caster)
				UnitRemoveAbility(caster,ReturnFastGoldID)

			end)
			--print("способность скастована")
		end
	end)
end

function InitDamageGold()
	local DamageTrigger = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
		TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
	end
	TriggerAddAction(DamageTrigger, function()
		local damage     = GetEventDamage() -- число урона
		if damage < 1 then return end
		local eventId         = GetHandleId(GetTriggerEventId())
		local isEventDamaged  = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)
		local target          = GetTriggerUnit() -- тот кто получил урон
		local caster          = GetEventDamageSource() -- тот кто нанёс урон


		if isEventDamaged then
			if GetUnitAbilityLevel(target,GoldReturnID)>0 then
				BlzSetEventDamage(0)
				UnitRemoveAbility(target,GoldReturnID)
				--print("попал")
				if GetOwningPlayer(target)==GetOwningPlayer(caster) and GetUnitAbilityLevel(target,FourCC("Argl"))>0 then
					--print("Золото долетело, даём деньги")
					FlyTextTagGoldBounty(target,"+10",GetOwningPlayer(target))
					AdjustPlayerStateBJ(10, GetOwningPlayer(target), PLAYER_STATE_RESOURCE_GOLD)
				end

			end
		end
	end)
end