---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.09.2020 11:29
---



do
	--Инициализация
	TimerStart(CreateTimer(), 0.11, false, function()
		--for i=0,bj_MAX_PLAYER_SLOTS-1 do
			InitAndUpdateMurgul(i)
		--end
	end)
end


function InitAndUpdateMurgul()
	local murguls=CreateGroup()
	local allMines=FindAllGoldMines()
	TimerStart(CreateTimer(), 0.7, true, function()
		--print("пытаемся проверить группу")
		ForGroup(allMines,function()
			local enum=GetEnumUnit()
			local e=nil
			--print("Поиск мурлоков для"..GetUnitName(enum)) --работает
			GroupEnumUnitsInRange(perebor,GetUnitX(enum),GetUnitY(enum),500)
			while true do
				e = FirstOfGroup(perebor)
				if e == nil then break end
				if UnitAlive(e) and GetUnitTypeId(e)==MurgulID then
					if not IsUnitInGroup(e,murguls) then
						GroupAddUnit(murguls,e)
					--	print("Мурлок найден и добавлен в группу")
					end
				end
				GroupRemoveUnit(perebor,e)
			end
		end)

		-----------А тепериь ищем покинувшего рудник
		ForGroup(murguls,function()
			--print("перебираем группу мурлоков")
			local enum=GetEnumUnit()
			local goldMine=FindUnitOfType(FourCC('ngol'),400,GetUnitX(enum),GetUnitY(enum))
			if OrderId2String(GetUnitCurrentOrder(enum))=="resumeharvesting" and IsUnitInRange(enum,goldMine,300) then
				UnitAddAbility(enum,ReturnFastGoldID)
				local base=FindUnitOfType(MainBaseID,700,GetUnitX(enum),GetUnitY(enum))
				IssueTargetOrder(enum,"acidbomb",base)
				--print("Определён мурлок с мешком золота, бросаем мешок в ратушу")
			end
		end)
		--DestroyGroup(murguls)
	end)
end


-- 1 раз за игру ищем все рудники
function FindAllGoldMines()
	local allMines=CreateGroup()
	local k=0
	local e=nil
	GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if UnitAlive(e) and GetUnitTypeId(e)==FourCC('ngol')  then
			--print("шахта добавлдена в группу")
			GroupAddUnit(allMines,e)
			k=k+1

		end
		GroupRemoveUnit(perebor,e)
	end
	--print("Найденно шахт: "..k)
	return allMines,k
end