---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.09.2020 20:44
---ANha
function ClearSourceState(unit)
	local success=false
	if GetUnitAbilityLevel(unit,ReturnFastGoldID)>0 then
		local savedPlayer=GetOwningPlayer(unit)
		success=true
		--UnitRemoveAbility(unit,FourCC("ANha"))
		--print("попытка отобрать золото")
		local x,y,f=GetUnitX(unit),GetUnitY(unit),GetUnitFacing(unit)
		KillUnit(unit)
		ShowUnit(unit,false)
		--SetUnitOwner(unit,Player(23),false)
		--UnitAddAbility(unit,FourCC("Argl")) --возвращаем ресурсы самому себе
		--IssueImmediateOrder(unit,"resumeharvesting")
		--TimerStart(CreateTimer(), 0.1, false, function()-- если не сделать задержку, то мешок не удаляется, НЕ ТРОГАТЬ 0.1
			--SetUnitOwner(unit,savedPlayer,false)
			--UnitRemoveAbility(unit,FourCC("Argl"))

		local new=CreateUnit(savedPlayer,MurgulID,x,y,f)
		local goldMine=FindUnitOfType(FourCC('ngol'),400,GetUnitX(new),GetUnitY(new))
		IssueTargetOrder(new,"smart",goldMine)




		--end)
	end
	return success
end