---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.10.2020 15:33
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitCasDevour()
    end)
end

tableDevour={}

function InitCasDevour()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        local unit=GetTriggerUnit()
        local target=GetSpellTargetUnit()
        if GetSpellAbilityId() == AbilityDevour then
            print("Уровень существа="..GetUnitLevel(target))
            if GetUnitLevel(target)>5 then
                FlyTextTagMiss(unit,"Это существо выше 5 уровня",GetOwningPlayer(unit))
                TimerStart(CreateTimer(), 0.1, false, function()
                    BlzStartUnitAbilityCooldown(unit,AbilityDevour,3)

                end)
                return
            end
            local damage=10
            local cdi=GetUnitState(target,UNIT_STATE_LIFE)//damage

            --print("Время на переваривание "..cdi)
            tableDevour[GetHandleId(unit)]=target
            ShowUnit(target,false)
            BlzPauseUnitEx(target,true)
            BlzUnitHideAbility(unit,AbilityDevour,true)
            UnitAddAbility(unit,AbilityDevourIndicator)
            UnitAddAbility(unit,AbilityDevourOut)
            BlzStartUnitAbilityCooldown(unit,AbilityDevourIndicator,cdi)
            local sec=0
            TimerStart(CreateTimer(), 1, true, function()
                if  IsUnitHidden(target) then
                    SetUnitPosition(target,GetUnitXY(unit))
                    UnitDamageTarget( unit, target, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
                    HealUnit(unit,damage)
                end
                sec=sec+1
                if sec>cdi or not IsUnitHidden(target) or not UnitAlive(target) then
                    DestroyTimer(GetExpiredTimer())
                    BlzUnitHideAbility(unit,AbilityDevour,false)
                    UnitRemoveAbility(unit,AbilityDevourIndicator)
                    UnitRemoveAbility(unit,AbilityDevourOut)
                    BlzPauseUnitEx(target,false)
                    --ShowUnit(target,true)
                end
            end)
        end
        if GetSpellAbilityId() == AbilityDevourOut then
            target=tableDevour[GetHandleId(unit)]
            local x,y=GetSpellTargetX(),GetSpellTargetY()
            local angle=-180+(AngleBetweenXY(x,y,GetUnitXY(unit))/bj_DEGTORAD)
            local dist=DistanceBetweenXY(x,y,GetUnitXY(unit))
            ShowUnit(target,true)
            SetUnitPosition(target,MoveXY(GetUnitX(unit),GetUnitY(unit),100,angle))
            --print("Запускаем юнита")
            BlzPauseUnitEx(target,true)
            UnitAddForce(target,angle,40,dist-200,400,1,unit)
            TimerStart(CreateTimer(), 0.1, false, function()
                SetUnitAnimation(unit,"stand")
                IssueImmediateOrder(unit,"stop")
            end)
        end
    end)
end
