---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.10.2020 15:33
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitCastEating()
    end)
end

function InitCastEating()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        local unit=GetTriggerUnit()
        if BlzGetUnitAbilityCooldownRemaining(unit,AbilityMaaHealID)<=.01 and GetUnitAbilityLevel(unit,AbilityMaaHealID)>0  then
            BlzStartUnitAbilityCooldown(unit,AbilityMaaHealID,30)
            --print("распыляем трупы")
            local e=nil
            local isHeal=false
            GroupEnumUnitsInRange(perebor,GetUnitX(unit),GetUnitY(unit),200,nil)
            while true do
                e = FirstOfGroup(perebor)
                if e == nil then break end
                if not UnitAlive(e) and not IsUnitType(e,UNIT_TYPE_MECHANICAL) then
                   -- print("найден труп")
                    ShowUnit(e,false)
                    isHeal=true

                end
                GroupRemoveUnit(perebor,e)
            end
            if isHeal then
                local eff=AddSpecialEffect("Objects\\Spawnmodels\\Human\\HumanSmallDeathExplode\\HumanSmallDeathExplode",GetUnitXY(unit))
                BlzSetSpecialEffectScale(eff,2)
                --BlzSetSpecialEffectMatrixScale(eff,4,4,2)
                GroupEnumUnitsInRange(perebor,GetUnitX(unit),GetUnitY(unit),200,nil)
                while true do
                    e = FirstOfGroup(perebor)
                    if e == nil then break end
                    if  UnitAlive(e) and not IsUnitType(e,UNIT_TYPE_MECHANICAL) and GetOwningPlayer(e)==GetOwningPlayer(unit) then
                        local amount=BlzGetUnitMaxHP(e)*.1
                        HealUnit(e,amount)

                    end
                    GroupRemoveUnit(perebor,e)
                end
            end
        end
    end)

    local ThisClick = CreateTrigger()
    TriggerRegisterCommandEvent(ThisClick, FourCC("A006"), "cannibalize")
    TriggerAddAction(ThisClick, function()
            --print("1111")
        local unit=GetTriggerUnit()
        local show=true
        local e=nil
        GroupEnumUnitsInRange(perebor,GetUnitX(unit),GetUnitY(unit),800,nil)
        while true do
            e = FirstOfGroup(perebor)
            if e == nil then break end
            if not UnitAlive(e) and not IsUnitType(e,UNIT_TYPE_MECHANICAL) then
                show=false
            end
            GroupRemoveUnit(perebor,e)
        end
        if show then
            FlyTextTagMiss(unit,"Нет трупов в радиусе",GetOwningPlayer(unit))
            AddCircleAreaForUnit(GetTriggerUnit(),1800,2)
        end
    end)
end
